project:
  type: website
  output-dir: docs

website:
  title: "Marianaep"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentary.qmd
        text: Documentary 
      - href: Blog.qmd
        text: Blog
      - href: cv-mariana-escobar.pdf
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual




